### ISSUE TITLE
enquiry about the mail sending feature

### ISSUE THREAD

**Issue by timoyuen** [athyuttamre/tab-snooze#27]
dear @athyuttamre 

this is a great chrome extension which helps me organize and manage everlasting pending tabs. 
thanks.

i am interested to see the mail sending function.

are you using some free smtp gateway? or some paid one? if so, will later this extension need charge some days later.

**Comment by athyuttamre** [comment]
Hi there, at the moment there isn't a mail sending feature in Tab Snooze. Perhaps you're confusing this with the other tabsnooze (www.tabsnooze.com)?

**Comment by valerio1** [comment]
Thsi is your tab-snooze? http://athyuttamreddy.com/tab-snooze/

and...

this is the other one?? http://www.tabsnooze.com/

**Comment by athyuttamre** [comment]
Yup, unfortunately. I used the name in the beginning, and it seems there was an unfortunate coincidence. You're right though, perhaps I should.
