### ISSUE TITLE
Breaks TravisCI when Authenticated with GitHub

### ISSUE THREAD

**Issue by adamgoose** [athyuttamre/tab-snooze#29]
For some reason, TabSnooze breaks http://travis-ci.org when logged into GitHub. It makes the entire screen 100% white.

**Comment by athyuttamre** [comment]
Hi @adamgoose, are you sure it's this app that's breaking it? There's an (unfortunately) identically named extension that does the same thing: www.tabsnooze.com.

**Comment by adamgoose** [comment]
Lol my bad. Good call. Close issue.

-- 
Adam Engebretson
Sent with Airmail

On January 16, 2015 at 11:24:15 AM, Athyuttam Reddy (notifications@github.com) wrote:

Hi @adamgoose, are you sure it's this app that's breaking it? There's an (unfortunately) identically named extension that does the same thing: www.tabsnooze.com.
