### ISSUE TITLE
Use Chrome alarms instead of window.setInterval

### ISSUE THREAD

**Issue by JannesMeyer** [athyuttamre/tab-snooze#31]
Chrome supports waking up an event page at a specific time:
https://developer.chrome.com/extensions/alarms

By using that we wouldn't need the background script to be persistent and could switch to an event page:
https://developer.chrome.com/extensions/event_pages

That would save a lot of RAM when the extension is inactive.

**Comment by athyuttamre** [comment]
Thanks for the suggestion, Jannes! 

I actually started with Chrome alarms, and discovered that they aren't always accurate (Chrome reserves the right to delay alarms indefinitely.) When I was testing alarms, they often got delayed by 30 minutes to 1 day. Wish they were better though!

**Comment by JannesMeyer** [comment]
Thanks for the quick reply, athyuttamre!

When was the last time you tested the alarms, though? I took a look at [alarm_manager.cc](https://chromium.googlesource.com/chromium/src/+/ace486916d2771c6e73402ce99c4f6cd3527cbee/extensions/browser/api/alarms/alarm_manager.cc) in the Chromium source and that file has been last updated three weeks ago. So there are definitely changes trickling down to stable continuously.
