### ISSUE TITLE
Safari extension?

### ISSUE THREAD

**Issue by michalkos** [athyuttamre/tab-snooze#9]
Love this idea! Any chance of implementing this also to Safari extension in the future?

**Comment by jDeppen** [comment]
+1

**Comment by pizzayap** [comment]
+1

**Comment by adamsimms** [comment]
+1

**Comment by ghost** [comment]
Yes, please make one for Safari!

**Comment by ghost** [comment]
Chrome is becoming a resource... pig.

**Comment by athyuttamre** [comment]
Hey everyone, wish I could maintain this project, but it is now deprecated. I also want to make sure you're not confusing this open source repo with [this extension](https://chrome.google.com/webstore/detail/tab-snooze/pdiebiamhaleloakpcgmpnenggpjbcbm?hl=en), which is developed separately by a different developer.
